### ISSUE TITLE
How to handle uiowa_events_paragraph module

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa_events#1]
Should the uiowa_events_paragraph sub-module continue to be a part of the uiowa_events module? Leaving it as part of this module presents the issue of its dependency on the uiowa_paragraphs module, which is, for now, still a part of the sitenow.

**Comment by pyrello** [comment]
At this point, I'm inclined to think that uiowa_events_paragraph should live alongside the relevant paragraphs implementation. In the case of sitenow, that would mean it would be added as a sub-module to the embedded uiowa_paragraphs module. Since it is my hope to develop a standalone set of modules (not embedded in a profile) for handling the paragraphs implementation used in the collegiate profile, there would be a version of uiowa_events_paragraph in there too.

**Comment by richardbporter** [comment]
I would agree. I think the base module should hold code that developers can implement in different ways. Functions/classes for getting events, caching them, etc.

**Comment by richardbporter** [comment]
@pyrello Did you want to transfer this to uiowa/uiowa? I would imagine uiowa_events_paragraph would go away once we migrate all sites to SNv3.

**Comment by pyrello** [comment]
@richardbporter I don't think this is an issue anymore since we are using only one D8 solution.
